name: CI/CD Pipeline for history-service Service

on:
  pull_request:
    branches:
      - backend-deploy
    paths:
      - "apps/backend/history-service/**"
  push:
    branches:
      - backend-deploy
    paths:
      - "apps/backend/history-service/**"

defaults:
  run:
    working-directory: apps/backend/history-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all branches and tags are fetched

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the version of Node.js that your project requires

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Run build
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./apps/backend/history-service/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/backend-deploy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./apps/backend/history-service/build

      - name: Prepare Deployment Directories
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }} # Update as per your setup
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/ubuntu/apps/history-service/build
            mkdir -p /home/ubuntu/apps/history-service/build/configs

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }} # Update as per your setup
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./apps/backend/history-service/build/*"
          target: "/home/ubuntu/apps/history-service/build"
          strip_components: 4

      - name: Create .env File
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }} # Update as per your setup
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> /home/ubuntu/apps/history-service/build/configs/.env.production
            echo "PORT=${{ secrets.HISTORY_SERVICE_PORT }}" >> /home/ubuntu/apps/history-service/build/configs/.env.production
            echo "MONGODB_URL=${{ secrets.MONGODB_HISTORY_SERVICE }}" >> /home/ubuntu/apps/bmi-service/build/configs/.env.production

      - name: Install Dependencies and Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }} # Update as per your setup
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Load the full user environment for non-interactive shells
            source /home/ubuntu/.nvm/nvm.sh
            source /home/ubuntu/.profile

            cd /home/ubuntu/apps/history-service/build
            yarn install --production

            # Check if the PM2 process is running
            if pm2 show history-service > /dev/null; then
              echo "Application is running. Restarting..."
              yarn restart
            else
              echo "Application is not running. Starting..."
              yarn start:pm2-production
            fi
